### **Python** y ambientes virtuales

In [23]:
print('Hola Mundo')

Hola Mundo

Importamos la librería de python para conectarnos a Neo4j

In [24]:
# Importar la librería de neo4j
from neo4j import GraphDatabase

Abrimos una conexión a Neo4j a la instancia activa y la base de datos que querremos usar

In [25]:
#Conexión a la base de datos a utilizar 
uri = "neo4j://127.0.0.1:7687"
user = "neo4j"
password = "12345678"
DB = "shv"

try:
    driver = GraphDatabase.driver(uri, auth=(user, password))

    with driver.session() as sesion:
        result = sesion.run("RETURN 1")
        if result.single()[0] ==1:
            print("Conexión exitosa a Neo4j")

except:
    print("Falló la conexión")

Conexión exitosa a Neo4j

Creamos una consulta en cypher que use la coneixón activa y nos regrese el nombre de los Villanos como una lista

In [26]:
query = """
    MATCH (v:Villian)
    RETURN v.Name AS Villanos;
"""

def run_read(tx, q, p=None):
    return list(tx.run(q, p or {}))

try:
    with driver.session(database=DB) as sesion:
        records = sesion.execute_read(run_read, query)
        rows = [r["Villanos"] for r in records]
        print(f"Villanos: \n {rows}")
       
finally:
    #driver.close()
    print("Conexión a Neo4j cerrada")

Villanos:
 ['Joker', 'Lex Luthor', 'Bane', 'Darkseid', 'Siniestro', 'Lobo', 'Deathstroke', 'Harley Quinn', 'Catwoman', 'Braniac', 'Flash Rebirth', 'Bizarro', 'Grodd', 'Black Manta', 'Zod', 'Cheetah', 'Abomination', 'Viper', 'Ultron', 'Venom', 'Green Goblin', 'Thanos', 'Loki', 'Red Skull', 'Doctor Doom']
Conexión a Neo4j cerrada

Creamos una consulta en cypher que use la coneixón activa y nos regrese el nombre de los Villanos en una columna. Solo mostramos los primeros tres.

In [27]:
query = """
    MATCH (v:Villian)
    RETURN v.Name AS Villanos
    LIMIT 3;
"""

with driver.session(database=DB) as sesion:
    records = sesion.execute_read(run_read, query)
    rows = [r["Villanos"] for r in records]

print("Villanos")
print("--------")
for Villanos in rows:
    print(Villanos)

Villanos
--------
Joker
Lex Luthor
Bane

Cerramos la conexión abierta con el driver de neo4j

In [28]:
    driver.close()
    print("Conexión hecha con el driver de Neo4j cerrada")

Conexión hecha con el driver de Neo4j cerrada

#### Creamos una conexión a Neo4j usando el driver Graph Data Science

Importamos las librerías necearias

In [29]:
import pandas as pd

from graphdatascience import GraphDataScience

Creamos una conexión de python a Neo4j usando la librería Graph Data Science

In [30]:
uri = "neo4j://127.0.0.1:7687"
user ="neo4j"
password = "12345678"
DB = "shv"

try:
    gds = GraphDataScience(uri, auth=(user, password))

    gds.set_database(DB)

    test = gds.run_cypher("RETURN 1 as prueba")
    if test['prueba'].iloc[0] ==1:
        print("Conexión exitosa a Neo4j")

except:
    print("Falló la conexión")

Conexión exitosa a Neo4j

Corremos una consulta simple en cypher y mostramos el resultado

In [31]:
gds.run_cypher("RETURN 'Hola Mundo' AS Mensaje")

      Mensaje
0  Hola Mundo

Corremos la consulta en cypher que muestra los villanos en una columna. Mostramos solo los primeros tres.

In [32]:
query = """
    MATCH (v:Villian)
    RETURN v.Name AS Villanos
    LIMIT 3;
"""

gds.run_cypher(query)

     Villanos
0       Joker
1  Lex Luthor
2        Bane

Creamos una consulta que muestre el total de Villanos

In [33]:
query = """
    MATCH (v:Villian)
    RETURN COUNT(DISTINCT v.Name) AS NumVillanos;
"""

gds.run_cypher(query)

   NumVillanos
0           25

Podemos aplicar casi todo lo visto desde este libro Jupiter que incluye código de Cypher y de Python

In [34]:
query = """
    MATCH (v:Villian)-[r]->(ov:Villian)
    RETURN v, r, ov
"""

gds.run_cypher(query)

,v,r,ov
0,"(louvain, pageRank, K1color, closeness_central...",(Weight),"(louvain, pageRank, K1color, closeness_central..."
1,"(louvain, pageRank, K1color, closeness_central...",(Weight),"(louvain, pageRank, K1color, closeness_central..."
2,"(louvain, pageRank, K1color, closeness_central...",(Weight),"(louvain, pageRank, K1color, closeness_central..."
3,"(louvain, pageRank, K1color, closeness_central...",(Cost),"(louvain, pageRank, K1color, closeness_central..."
4,"(louvain, pageRank, K1color, closeness_central...",(score),"(louvain, pageRank, K1color, closeness_central..."
...,...,...,...
94,"(louvain, pageRank, K1color, closeness_central...",(Weight),"(louvain, pageRank, K1color, closeness_central..."
95,"(louvain, pageRank, K1color, closeness_central...",(Cost),"(louvain, pageRank, K1color, closeness_central..."
96,"(louvain, pageRank, K1color, closeness_central...",(score),"(louvain, pageRank, K1color, closeness_central..."
97,"(louvain, pageRank, K1color, closeness_central...",(score),"(louvain, pageRank, K1color, closeness_central..."
98,"(louvain, pageRank, K1color, closeness_central...",(score),"(louvain, pageRank, K1color, closeness_central..."